# Generated by Django 3.1.7 on 2021-02-23 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
